spring:
  application:
    name: backend
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: shoplab
    password: shoplab1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true